# Generated by Django 6.1 on 2026-08-25 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('org_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='reconciliation.org')),
            ],
        ),
        migrations.CreateModel(
            name='SystemARecord',
            fields=[
                ('record_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('location_id_raw', models.CharField(blank=True, max_length=64)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('event_date_raw', models.CharField(blank=True, max_length=64)),
                ('category_code', models.CharField(blank=True, max_length=32)),
                ('actor_id', models.CharField(blank=True, max_length=32)),
                ('base_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('adjustment', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('total_value_raw', models.CharField(blank=True, max_length=64)),
                ('state', models.CharField(blank=True, max_length=32)),
                ('import_issues', models.JSONField(blank=True, default=list)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a_records', to='reconciliation.location')),
            ],
            options={
                'ordering': ['record_id'],
            },
        ),
        migrations.CreateModel(
            name='SystemBEntry',
            fields=[
                ('entry_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('record_ref_raw', models.CharField(max_length=64)),
                ('record_ref_normalized', models.CharField(blank=True, max_length=32, null=True)),
                ('location_id_raw', models.CharField(blank=True, max_length=64)),
                ('recorded_on', models.DateField(blank=True, null=True)),
                ('recorded_on_raw', models.CharField(blank=True, max_length=64)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('value_raw', models.CharField(blank=True, max_length=64)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('import_issues', models.JSONField(blank=True, default=list)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='b_entries', to='reconciliation.location')),
                ('matched_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='b_entries', to='reconciliation.systemarecord')),
            ],
            options={
                'verbose_name_plural': 'System B entries',
                'ordering': ['entry_id'],
            },
        ),
    ]
